---
- hosts: all
  vars:
    all_ifaces: []

  tasks:
    - set_fact:
        docker_minimal_version: "19.03"
        control_plane_node: wk000
        kubeconfig: /etc/kubernetes/admin.conf

    - set_fact:
        is_control_plane_node: "{{ ansible_nodename == control_plane_node }}"

    - set_fact:
        all_ifaces: "{{ all_ifaces + [vars['ansible_' + item]] }}"
      with_items: "{{ ansible_interfaces }}"

    - set_fact:
        current_iface: "{{ all_ifaces | selectattr('ipv4.address', 'equalto', ansible_host) | first }}"

    - set_fact:
        flannel: "{{ lookup('file', 'kube-flannel.yml') | from_yaml_all | list }}"

    - set_fact:
        flannel_config_map: "{{ flannel | selectattr('kind', 'equalto', 'ConfigMap') | first }}"

    - set_fact:
        flannel_config_map_data: "{{ flannel_config_map.data['net-conf.json'] | from_json }}"

    - set_fact:
        pod_network_cidr: "{{ flannel_config_map_data['Network'] }}"

    - name: Install common tools
      apt:
        update_cache: yes
        name:
          - net-tools
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - python3-pip
      become: yes

    - name: Install openshift (needed fro k8s_info)
      pip:
        name: openshift
      become: yes

    - name: Add the br_netfilter module
      modprobe:
        name: br_netfilter
        state: present
      become: yes

    - name: Ensure net.bridge.bridge-nf-call-iptables is set to 1 in your sysctl config
      copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          br_netfilter
      become: yes

    - name: Ensure net.bridge.bridge-nf-call-iptables is set to 1 in your sysctl config
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
      become: yes

    - name: Add Docker’s official GPG key
      apt_key:
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: yes

    - apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
      become: yes

    - name: Create the `docker` group
      group:
        name: docker
        state: present
      become: yes

    - name: Add your user to the `docker` group.
      user:
        append: yes
        groups:
          - docker
        name: "{{ ansible_user }}"
      become: yes

    - name: Install docker
      apt:
        update_cache: yes
        name:
          - "docker-ce=5:{{ docker_minimal_version }}*"
          - "docker-ce-cli=5:{{ docker_minimal_version }}*"
          - containerd.io
      become: yes

    - name: Docker config
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "exec-opts": ["native.cgroupdriver=systemd"],
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "100m"
            },
            "storage-driver": "overlay2"
          }
      register: docker_daemon_json
      become: yes

    - file:
        path : /etc/systemd/system/docker.service.d
        recurse: true
        state: directory
        owner: root
      become: yes

    - name: Restart docker service
      systemd:
        name: docker
        state: restarted
        daemon_reload: yes
      when: docker_daemon_json.changed
      become: yes

    # - name: Detect k8s stable version
    #   uri:
    #     url: https://dl.k8s.io/release/stable.txt
    #     return_content: yes
    #   register: k8s_stable

    # - name: Download kubectl
    #   get_url:
    #     dest: /usr/local/bin/kubectl
    #     url: "https://dl.k8s.io/release/{{ k8s_stable.content }}/bin/linux/amd64/kubectl"
    #     checksum: "sha256:https://storage.googleapis.com/kubernetes-release/release/{{ k8s_stable.content }}/bin/linux/amd64/kubectl.sha256"
    #     owner: root
    #     group: root
    #     mode: '0755'

    - name: Add k8s official GPG key
      apt_key:
        id: 54A647F9048D5688D7DA2ABE6A030B21BA07F4FB
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
      become: yes

    - apt_repository:
        filename: kubernetes.list
        repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
        state: present
      become: yes

    - name: Install k8s
      apt:
        update_cache: yes
        name:
          - kubelet
          - kubeadm
          - kubectl
      become: yes

##### On control pane node

    - name: Setup cluster
      shell:
        cmd: "kubeadm init --apiserver-advertise-address {{ ansible_host }} --pod-network-cidr {{ pod_network_cidr }}"
        creates: "{{ kubeconfig }}"
      become: yes
      when: is_control_plane_node

    - name: Save config locally
      fetch:
        src: "{{ kubeconfig }}"
        dest: "{{ lookup('pipe', 'pwd') }}/"
        flat: yes
      become: yes
      when: is_control_plane_node

    - name: Save admin kubeconfig content
      slurp:
        src: "{{ kubeconfig }}"
      register: admin_kubeconfig
      become: yes
      when: is_control_plane_node

    - name: Install flannel CNI
      k8s:
        state: present
        kubeconfig: "{{ kubeconfig }}"
        definition: "{{ flannel }}"
      when: is_control_plane_node
      become: yes

    - name: Get join command
      shell:
        cmd: kubeadm token create --print-join-command
      register: kubeadm_join_command
      become: yes
      when: is_control_plane_node

##### On other nodes

    - name: Join other nodes
      shell:
        cmd: "{{ hostvars[control_plane_node].kubeadm_join_command.stdout }}"
        creates: /etc/kubernetes/kubelet.conf
      when: not is_control_plane_node
      become: yes

    - name: Copy admin config from control plane node
      copy:
        content: "{{ hostvars[control_plane_node].admin_kubeconfig.content | b64decode }}"
        dest: "{{ kubeconfig }}"
      when: not is_control_plane_node
      become: yes

################################################################################

    - name: Create a ~/.kube directory if it does not exist
      file:
        path: "{{ ansible_user_dir }}/.kube"
        state: directory

    - name: Move config
      copy:
        remote_src: yes
        src: /etc/kubernetes/admin.conf
        dest: "{{ ansible_user_dir }}/.kube/config"
        owner: "{{ ansible_effective_user_id }}"
        group: "{{ ansible_effective_group_id }}"
      become: yes
